name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull
      
    - name: Build and publish Docker Image to new GitHub Packages Registry
      # You may pin to the exact commit or the version.
      # uses: DrSkunk/gp-docker-action@96d519ce38c92b59319041ad2a8f80f0e3974d82
      uses: DrSkunk/gp-docker-action@1.1.9
      with:
        # GitHub token to push Docker image to GitHub Packages
        github-token: ${{ secrets.GH_TOKEN }}
        # Docker Image name
        image-name: kepler
        # Docker Image tag
        image-tag: $(date +%s)
